### ISSUE TITLE
Implement the rest API

### ISSUE THREAD

**Issue by VovaStelmashchuk** [JeroenGar/jagua-rs#1]
First of all, thx for creating the project. 

I made my own fork, and implement the rest api service based on your app.
You can see my code [here](https://github.com/VovaStelmashchuk/jagua-rs). 

Can I interested you in merge such functionality into origin repository ?

**Comment by JeroenGar** [comment]
While I genuinely appreciate your interest in the project, I do not see the added value of adding a REST API to the LBF crate in the main repo.
The LBF heuristic is meant to serve as a reference, demonstrating how to interact with `jagua-rs`, and certainly not to be deployed in practice.
It is essential to keep this crate as lean as possible.

I would suggest you to separate the REST API code outside of the LBF crate and publish it as a separate project with this repo as a submodule.

**Comment by VovaStelmashchuk** [comment]
I see you point.
I keeping developing into my own fork.
